package defpackage;

import ch.qos.logback.core.CoreConstants;
import ch.qos.logback.core.joran.action.Action;
import com.huawei.hms.opendevice.c;
import java.util.Hashtable;
import org.bouncycastle.asn1.k;
/* renamed from: a39  reason: default package */
/* loaded from: classes3.dex */
public class a39 extends n2 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    private static final Hashtable T;
    private static final Hashtable U;
    public static final u9c V;
    public static final k c;
    public static final k d;
    public static final k e;
    public static final k f;
    public static final k g;
    public static final k h;
    public static final k i;
    public static final k j;
    public static final k k;
    public static final k l;
    public static final k m;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;
    protected final Hashtable b = n2.e(T);
    protected final Hashtable a = n2.e(U);

    static {
        k O2 = new k("2.5.4.15").O();
        c = O2;
        k O3 = new k("2.5.4.6").O();
        d = O3;
        k O4 = new k("2.5.4.3").O();
        e = O4;
        k O5 = new k("0.9.2342.19200300.100.1.25").O();
        f = O5;
        k O6 = new k("2.5.4.13").O();
        g = O6;
        k O7 = new k("2.5.4.27").O();
        h = O7;
        k O8 = new k("2.5.4.49").O();
        i = O8;
        k O9 = new k("2.5.4.46").O();
        j = O9;
        k O10 = new k("2.5.4.47").O();
        k = O10;
        k O11 = new k("2.5.4.23").O();
        l = O11;
        k O12 = new k("2.5.4.44").O();
        m = O12;
        k O13 = new k("2.5.4.42").O();
        n = O13;
        k O14 = new k("2.5.4.51").O();
        o = O14;
        k O15 = new k("2.5.4.43").O();
        p = O15;
        k O16 = new k("2.5.4.25").O();
        q = O16;
        k O17 = new k("2.5.4.7").O();
        r = O17;
        k O18 = new k("2.5.4.31").O();
        s = O18;
        k O19 = new k("2.5.4.41").O();
        t = O19;
        k O20 = new k("2.5.4.10").O();
        u = O20;
        k O21 = new k("2.5.4.11").O();
        v = O21;
        k O22 = new k("2.5.4.32").O();
        w = O22;
        k O23 = new k("2.5.4.19").O();
        x = O23;
        k O24 = new k("2.5.4.16").O();
        y = O24;
        k O25 = new k("2.5.4.17").O();
        z = O25;
        k O26 = new k("2.5.4.18").O();
        A = O26;
        k O27 = new k("2.5.4.28").O();
        B = O27;
        k O28 = new k("2.5.4.26").O();
        C = O28;
        k O29 = new k("2.5.4.33").O();
        D = O29;
        k O30 = new k("2.5.4.14").O();
        E = O30;
        k O31 = new k("2.5.4.34").O();
        F = O31;
        k O32 = new k("2.5.4.5").O();
        G = O32;
        k O33 = new k("2.5.4.4").O();
        H = O33;
        k O34 = new k("2.5.4.8").O();
        I = O34;
        k O35 = new k("2.5.4.9").O();
        J = O35;
        k O36 = new k("2.5.4.20").O();
        K = O36;
        k O37 = new k("2.5.4.22").O();
        L = O37;
        k O38 = new k("2.5.4.21").O();
        M = O38;
        k O39 = new k("2.5.4.12").O();
        N = O39;
        k O40 = new k("0.9.2342.19200300.100.1.1").O();
        O = O40;
        k O41 = new k("2.5.4.50").O();
        P = O41;
        k O42 = new k("2.5.4.35").O();
        Q = O42;
        k O43 = new k("2.5.4.24").O();
        R = O43;
        k O44 = new k("2.5.4.45").O();
        S = O44;
        Hashtable hashtable = new Hashtable();
        T = hashtable;
        Hashtable hashtable2 = new Hashtable();
        U = hashtable2;
        hashtable.put(O2, "businessCategory");
        hashtable.put(O3, c.a);
        hashtable.put(O4, "cn");
        hashtable.put(O5, "dc");
        hashtable.put(O6, "description");
        hashtable.put(O7, "destinationIndicator");
        hashtable.put(O8, "distinguishedName");
        hashtable.put(O9, "dnQualifier");
        hashtable.put(O10, "enhancedSearchGuide");
        hashtable.put(O11, "facsimileTelephoneNumber");
        hashtable.put(O12, "generationQualifier");
        hashtable.put(O13, "givenName");
        hashtable.put(O14, "houseIdentifier");
        hashtable.put(O15, "initials");
        hashtable.put(O16, "internationalISDNNumber");
        hashtable.put(O17, "l");
        hashtable.put(O18, "member");
        hashtable.put(O19, Action.NAME_ATTRIBUTE);
        hashtable.put(O20, "o");
        hashtable.put(O21, "ou");
        hashtable.put(O22, "owner");
        hashtable.put(O23, "physicalDeliveryOfficeName");
        hashtable.put(O24, "postalAddress");
        hashtable.put(O25, "postalCode");
        hashtable.put(O26, "postOfficeBox");
        hashtable.put(O27, "preferredDeliveryMethod");
        hashtable.put(O28, "registeredAddress");
        hashtable.put(O29, "roleOccupant");
        hashtable.put(O30, "searchGuide");
        hashtable.put(O31, "seeAlso");
        hashtable.put(O32, "serialNumber");
        hashtable.put(O33, "sn");
        hashtable.put(O34, "st");
        hashtable.put(O35, "street");
        hashtable.put(O36, "telephoneNumber");
        hashtable.put(O37, "teletexTerminalIdentifier");
        hashtable.put(O38, "telexNumber");
        hashtable.put(O39, "title");
        hashtable.put(O40, "uid");
        hashtable.put(O41, "uniqueMember");
        hashtable.put(O42, "userPassword");
        hashtable.put(O43, "x121Address");
        hashtable.put(O44, "x500UniqueIdentifier");
        hashtable2.put("businesscategory", O2);
        hashtable2.put(c.a, O3);
        hashtable2.put("cn", O4);
        hashtable2.put("dc", O5);
        hashtable2.put("description", O6);
        hashtable2.put("destinationindicator", O7);
        hashtable2.put("distinguishedname", O8);
        hashtable2.put("dnqualifier", O9);
        hashtable2.put("enhancedsearchguide", O10);
        hashtable2.put("facsimiletelephonenumber", O11);
        hashtable2.put("generationqualifier", O12);
        hashtable2.put("givenname", O13);
        hashtable2.put("houseidentifier", O14);
        hashtable2.put("initials", O15);
        hashtable2.put("internationalisdnnumber", O16);
        hashtable2.put("l", O17);
        hashtable2.put("member", O18);
        hashtable2.put(Action.NAME_ATTRIBUTE, O19);
        hashtable2.put("o", O20);
        hashtable2.put("ou", O21);
        hashtable2.put("owner", O22);
        hashtable2.put("physicaldeliveryofficename", O23);
        hashtable2.put("postaladdress", O24);
        hashtable2.put("postalcode", O25);
        hashtable2.put("postofficebox", O26);
        hashtable2.put("preferreddeliverymethod", O27);
        hashtable2.put("registeredaddress", O28);
        hashtable2.put("roleoccupant", O29);
        hashtable2.put("searchguide", O30);
        hashtable2.put("seealso", O31);
        hashtable2.put("serialnumber", O32);
        hashtable2.put("sn", O33);
        hashtable2.put("st", O34);
        hashtable2.put("street", O35);
        hashtable2.put("telephonenumber", O36);
        hashtable2.put("teletexterminalidentifier", O37);
        hashtable2.put("telexnumber", O38);
        hashtable2.put("title", O39);
        hashtable2.put("uid", O40);
        hashtable2.put("uniquemember", O41);
        hashtable2.put("userpassword", O42);
        hashtable2.put("x121address", O43);
        hashtable2.put("x500uniqueidentifier", O44);
        V = new a39();
    }

    protected a39() {
    }

    @Override // defpackage.u9c
    public String b(t9c t9cVar) {
        StringBuffer stringBuffer = new StringBuffer();
        x29[] w2 = t9cVar.w();
        boolean z2 = true;
        for (int length = w2.length - 1; length >= 0; length--) {
            if (z2) {
                z2 = false;
            } else {
                stringBuffer.append(CoreConstants.COMMA_CHAR);
            }
            sr4.a(stringBuffer, w2[length], this.b);
        }
        return stringBuffer.toString();
    }
}
