package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: e50  reason: default package */
/* loaded from: classes3.dex */
public interface e50 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    public static final k T;
    public static final k U;
    public static final k V;
    public static final k W;
    public static final k X;
    public static final k Y;
    public static final k Z;
    public static final k a;
    public static final k a0;
    public static final k b;
    public static final k b0;
    public static final k c;
    public static final k c0;
    public static final k d;
    public static final k d0;
    public static final k e;
    public static final k e0;
    public static final k f;
    public static final k f0;
    public static final k g;
    public static final k g0;
    public static final k h;
    public static final k h0;
    public static final k i;
    public static final k j;
    public static final k k;
    public static final k l;
    public static final k m;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("1.3.6.1.4.1.22554");
        a = kVar;
        k D2 = kVar.D("1");
        b = D2;
        k D3 = D2.D("1");
        c = D3;
        k D4 = D2.D("2.1");
        d = D4;
        e = D2.D("2.2");
        f = D2.D("2.3");
        g = D2.D("2.4");
        h = D3.D("1");
        k D5 = D3.D("2");
        i = D5;
        j = D4.D("1");
        k D6 = D4.D("2");
        k = D6;
        l = D5.D("1.2");
        m = D5.D("1.22");
        n = D5.D("1.42");
        o = D6.D("1.2");
        p = D6.D("1.22");
        q = D6.D("1.42");
        k D7 = kVar.D("2");
        r = D7;
        k D8 = D7.D("1");
        s = D8;
        t = D8.D("1");
        u = D8.D("2");
        v = D8.D("3");
        k D9 = D7.D("2");
        w = D9;
        k D10 = D9.D("1");
        x = D10;
        k D11 = D9.D("2");
        y = D11;
        k D12 = D9.D("3");
        z = D12;
        k D13 = D9.D("4");
        A = D13;
        B = D9.D("5");
        C = D9.D("6");
        D = D9.D("7");
        E = D9.D("8");
        k D14 = D7.D("3");
        F = D14;
        k D15 = D14.D("1");
        G = D15;
        k D16 = D14.D("2");
        H = D16;
        I = D14.D("3");
        J = D14.D("4");
        K = D14.D("5");
        L = D14.D("6");
        k D17 = D14.D("7");
        M = D17;
        k D18 = D14.D("8");
        N = D18;
        O = D10;
        P = D11;
        Q = D12;
        R = D13;
        S = D15;
        T = D16;
        U = D17;
        V = D18;
        k D19 = D7.D("4");
        W = D19;
        X = D19.D("1");
        Y = D19.D("2");
        Z = D19.D("3");
        a0 = D19.D("4");
        b0 = D19.D("5");
        c0 = D19.D("11");
        d0 = D19.D("12");
        k D20 = kVar.D("3");
        e0 = D20;
        f0 = D20.D("1");
        k D21 = kVar.D("4");
        g0 = D21;
        h0 = D21.D("1");
    }
}
