package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: ko7  reason: default package */
/* loaded from: classes3.dex */
public interface ko7 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    public static final k T;
    public static final k U;
    public static final k V;
    public static final k W;
    public static final k X;
    public static final k Y;
    public static final k a;
    public static final k b;
    public static final k c;
    public static final k d;
    public static final k e;
    public static final k f;
    public static final k g;
    public static final k h;
    public static final k i;
    public static final k j;
    public static final k k;
    public static final k l;
    public static final k m;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("1.3.6.1.4.1.8301.3.1.3.5.3.2");
        a = kVar;
        b = kVar.D("1");
        c = kVar.D("2");
        d = kVar.D("3");
        e = kVar.D("4");
        f = kVar.D("5");
        k kVar2 = new k("1.3.6.1.4.1.8301.3.1.3.3");
        g = kVar2;
        h = kVar2.D("1");
        i = kVar2.D("2");
        j = kVar2.D("3");
        k = kVar2.D("4");
        l = kVar2.D("5");
        m = new k("1.3.6.1.4.1.8301.3.1.3.4.1");
        n = new k("1.3.6.1.4.1.8301.3.1.3.4.2");
        o = new k("1.3.6.1.4.1.8301.3.1.3.4.2.1");
        p = new k("1.3.6.1.4.1.8301.3.1.3.4.2.2");
        q = new k("1.3.6.1.4.1.8301.3.1.3.4.2.3");
        r = e50.s;
        s = e50.t;
        t = e50.u;
        u = e50.v;
        v = e50.f0;
        w = e50.w;
        k kVar3 = e50.x;
        x = kVar3;
        k kVar4 = e50.y;
        y = kVar4;
        k kVar5 = e50.z;
        z = kVar5;
        k kVar6 = e50.A;
        A = kVar6;
        B = e50.B;
        C = e50.C;
        D = e50.D;
        E = e50.E;
        F = e50.F;
        k kVar7 = e50.G;
        G = kVar7;
        k kVar8 = e50.H;
        H = kVar8;
        I = e50.I;
        J = e50.J;
        K = e50.K;
        L = e50.L;
        k kVar9 = e50.M;
        M = kVar9;
        k kVar10 = e50.N;
        N = kVar10;
        O = kVar3;
        P = kVar4;
        Q = kVar5;
        R = kVar6;
        S = kVar7;
        T = kVar8;
        U = kVar9;
        V = kVar10;
        W = e50.W;
        X = e50.c0;
        Y = e50.d0;
    }
}
