package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: ms6  reason: default package */
/* loaded from: classes3.dex */
public interface ms6 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    public static final k T;
    public static final k U;
    public static final k V;
    public static final k W;
    public static final k X;
    public static final k Y;
    public static final k Z;
    public static final k a;
    public static final k a0;
    public static final k b;
    public static final k b0;
    public static final k c;
    public static final k c0;
    public static final k d;
    public static final k d0;
    public static final k e;
    public static final k e0;
    public static final k f;
    public static final k f0;
    public static final k g;
    public static final k g0;
    public static final k h;
    public static final k h0;
    public static final k i;
    public static final k i0;
    public static final k j;
    public static final k j0;
    public static final k k;
    public static final k k0;
    public static final k l;
    public static final k l0;
    public static final k m;
    public static final k m0;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("2.16.840.1.101.3.4");
        a = kVar;
        k D2 = kVar.D("2");
        b = D2;
        c = D2.D("1");
        d = D2.D("2");
        e = D2.D("3");
        f = D2.D("4");
        g = D2.D("5");
        h = D2.D("6");
        i = D2.D("7");
        j = D2.D("8");
        k = D2.D("9");
        l = D2.D("10");
        m = D2.D("11");
        n = D2.D("12");
        o = D2.D("13");
        p = D2.D("14");
        q = D2.D("15");
        r = D2.D("16");
        s = D2.D("17");
        t = D2.D("18");
        u = D2.D("19");
        v = D2.D("20");
        k D3 = kVar.D("1");
        w = D3;
        x = D3.D("1");
        y = D3.D("2");
        z = D3.D("3");
        A = D3.D("4");
        B = D3.D("5");
        C = D3.D("6");
        D = D3.D("7");
        E = D3.D("8");
        F = D3.D("21");
        G = D3.D("22");
        H = D3.D("23");
        I = D3.D("24");
        J = D3.D("25");
        K = D3.D("26");
        L = D3.D("27");
        M = D3.D("28");
        N = D3.D("41");
        O = D3.D("42");
        P = D3.D("43");
        Q = D3.D("44");
        R = D3.D("45");
        S = D3.D("46");
        T = D3.D("47");
        U = D3.D("48");
        k D4 = kVar.D("3");
        V = D4;
        W = D4;
        X = D4.D("1");
        Y = D4.D("2");
        Z = D4.D("3");
        a0 = D4.D("4");
        b0 = D4.D("5");
        c0 = D4.D("6");
        d0 = D4.D("7");
        e0 = D4.D("8");
        f0 = D4.D("9");
        g0 = D4.D("10");
        h0 = D4.D("11");
        i0 = D4.D("12");
        j0 = D4.D("13");
        k0 = D4.D("14");
        l0 = D4.D("15");
        m0 = D4.D("16");
    }
}
