package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: oac  reason: default package */
/* loaded from: classes3.dex */
public interface oac {
    public static final k A3;
    public static final k A4;
    public static final k B3;
    public static final k B4;
    public static final k C3;
    public static final k C4;
    public static final k D3;
    public static final k D4;
    public static final k E3;
    public static final k E4;
    public static final k F3;
    public static final k F4;
    public static final k G3;
    public static final k G4;
    public static final k H3;
    public static final k I3;
    public static final k J3;
    public static final k K3;
    public static final k L3;
    public static final k M3;
    public static final k N3;
    public static final k O3;
    public static final k P3;
    public static final k Q3;
    public static final k R3;
    public static final k S3;
    public static final k T3;
    public static final k U3;
    public static final k V3;
    public static final k W3;
    public static final k X3;
    public static final k Y3;
    public static final k Z3;
    public static final k a4;
    public static final k b4;
    public static final k c4;
    public static final k d4;
    public static final k e4;
    public static final k f4;
    public static final k g4;
    public static final k h4;
    public static final k i4;
    public static final k j4;
    public static final k k4;
    public static final k l4;
    public static final k m4;
    public static final k n4;
    public static final k o4;
    public static final k p4;
    public static final k q4;
    public static final k r4;
    public static final k s3;
    public static final k s4;
    public static final k t3;
    public static final k t4;
    public static final k u3;
    public static final k u4;
    public static final k v3;
    public static final k v4;
    public static final k w3;
    public static final k w4;
    public static final k x3;
    public static final k x4;
    public static final k y3;
    public static final k y4;
    public static final k z3;
    public static final k z4;

    static {
        k kVar = new k("1.2.840.10045");
        s3 = kVar;
        k D = kVar.D("1");
        t3 = D;
        u3 = D.D("1");
        k D2 = D.D("2");
        v3 = D2;
        w3 = D2.D("3.1");
        x3 = D2.D("3.2");
        y3 = D2.D("3.3");
        k D5 = kVar.D("4");
        z3 = D5;
        A3 = D5.D("1");
        k D6 = kVar.D("2");
        B3 = D6;
        C3 = D6.D("1");
        k D7 = D5.D("3");
        D3 = D7;
        E3 = D7.D("1");
        F3 = D7.D("2");
        G3 = D7.D("3");
        H3 = D7.D("4");
        k D8 = kVar.D("3");
        I3 = D8;
        k D9 = D8.D("0");
        J3 = D9;
        K3 = D9.D("1");
        L3 = D9.D("2");
        M3 = D9.D("3");
        N3 = D9.D("4");
        O3 = D9.D("5");
        P3 = D9.D("6");
        Q3 = D9.D("7");
        R3 = D9.D("8");
        S3 = D9.D("9");
        T3 = D9.D("10");
        U3 = D9.D("11");
        V3 = D9.D("12");
        W3 = D9.D("13");
        X3 = D9.D("14");
        Y3 = D9.D("15");
        Z3 = D9.D("16");
        a4 = D9.D("17");
        b4 = D9.D("18");
        c4 = D9.D("19");
        d4 = D9.D("20");
        k D10 = D8.D("1");
        e4 = D10;
        f4 = D10.D("1");
        g4 = D10.D("2");
        h4 = D10.D("3");
        i4 = D10.D("4");
        j4 = D10.D("5");
        k4 = D10.D("6");
        l4 = D10.D("7");
        m4 = new k("1.2.840.10040.4.1");
        n4 = new k("1.2.840.10040.4.3");
        k kVar2 = new k("1.3.133.16.840.63.0");
        o4 = kVar2;
        p4 = kVar2.D("2");
        q4 = kVar2.D("3");
        r4 = kVar2.D("16");
        k kVar3 = new k("1.2.840.10046");
        s4 = kVar3;
        t4 = kVar3.D("2.1");
        k D11 = kVar3.D("3");
        u4 = D11;
        v4 = D11.D("1");
        w4 = D11.D("2");
        x4 = D11.D("3");
        y4 = D11.D("4");
        z4 = D11.D("5");
        A4 = D11.D("6");
        B4 = D11.D("7");
        C4 = D11.D("8");
        k kVar4 = new k("1.3.133.16.840.9.44");
        D4 = kVar4;
        k D12 = kVar4.D("1");
        E4 = D12;
        F4 = D12.D("1");
        G4 = D12.D("2");
    }
}
