package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: pl6  reason: default package */
/* loaded from: classes3.dex */
public interface pl6 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k a;
    public static final k b;
    public static final k c;
    public static final k d;
    public static final k e;
    public static final k f;
    public static final k g;
    public static final k h;
    public static final k i;
    public static final k j;
    public static final k k;
    public static final k l;
    public static final k m;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("2.16.840.1.113730.1");
        a = kVar;
        b = kVar.D("1");
        c = kVar.D("2");
        d = kVar.D("3");
        e = kVar.D("4");
        f = kVar.D("7");
        g = kVar.D("8");
        h = kVar.D("12");
        i = kVar.D("13");
        k kVar2 = new k("2.16.840.1.113733.1");
        j = kVar2;
        k = kVar2.D("6.3");
        l = kVar2.D("6.9");
        m = kVar2.D("6.11");
        n = kVar2.D("6.13");
        o = kVar2.D("6.15");
        p = kVar2.D("8.1");
        k kVar3 = new k("2.16.840.1.113719");
        q = kVar3;
        r = kVar3.D("1.9.4.1");
        k kVar4 = new k("1.2.840.113533.7");
        s = kVar4;
        t = kVar4.D("65.0");
        u = kVar4.D("66.10");
        v = new k("1.3.6.1.5.5.8.1.2");
        w = new k("1.3.6.1.4.1.188.7.1.1.2");
        k kVar5 = new k("1.3.6.1.4.1.3029");
        x = kVar5;
        k D2 = kVar5.D("1");
        y = D2;
        z = D2.D("1.1");
        A = D2.D("1.2");
        B = D2.D("1.3");
        C = D2.D("1.4");
        k kVar6 = new k("1.3.6.1.4.1.1722.12.2");
        D = kVar6;
        E = kVar6.D("1.5");
        F = kVar6.D("1.8");
        G = kVar6.D("1.12");
        H = kVar6.D("1.16");
        I = kVar6.D("2.4");
        J = kVar6.D("2.5");
        K = kVar6.D("2.7");
        L = kVar6.D("2.8");
        M = new k("1.3.6.1.4.1.11591.4.11");
        N = new k("1.3.6.1.4.1.18227.2.1");
    }
}
