package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: qa4  reason: default package */
/* loaded from: classes3.dex */
public interface qa4 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    public static final k T;
    public static final k U;
    public static final k V;
    public static final k W;
    public static final k X;
    public static final k Y;
    public static final k Z;
    public static final k a;
    public static final k a0;
    public static final k b;
    public static final k b0;
    public static final k c;
    public static final k c0;
    public static final k d;
    public static final k d0;
    public static final k e;
    public static final k e0;
    public static final k f;
    public static final k f0;
    public static final k g;
    public static final k g0;
    public static final k h;
    public static final k h0;
    public static final k i;
    public static final k i0;
    public static final k j;
    public static final k j0;
    public static final k k;
    public static final k k0;
    public static final k l;
    public static final k l0;
    public static final k m;
    public static final k m0;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("1.2.156.10197.1");
        a = kVar;
        b = kVar.D("101.1");
        c = kVar.D("101.2");
        d = kVar.D("101.3");
        e = kVar.D("101.4");
        f = kVar.D("102.1");
        g = kVar.D("102.2");
        h = kVar.D("102.3");
        i = kVar.D("102.4");
        j = kVar.D("102.5");
        k = kVar.D("102.6");
        l = kVar.D("103.1");
        m = kVar.D("103.2");
        n = kVar.D("103.3");
        o = kVar.D("103.4");
        p = kVar.D("103.5");
        q = kVar.D("103.6");
        r = kVar.D("104.1");
        s = kVar.D("104.2");
        t = kVar.D("104.3");
        u = kVar.D("104.4");
        v = kVar.D("104.5");
        w = kVar.D("104.6");
        x = kVar.D("104.7");
        y = kVar.D("104.8");
        z = kVar.D("104.9");
        A = kVar.D("104.10");
        B = kVar.D("104.11");
        C = kVar.D("104.12");
        D = kVar.D("104.100");
        E = kVar.D("201");
        F = kVar.D("301");
        G = kVar.D("301.1");
        H = kVar.D("301.2");
        k D2 = kVar.D("301.3");
        I = D2;
        J = kVar.D("301.101");
        K = D2.D("1");
        L = D2.D("2");
        M = D2.D("2.1");
        N = D2.D("2.2");
        O = D2.D("2.3");
        P = D2.D("2.4");
        Q = D2.D("2.5");
        R = D2.D("2.6");
        S = D2.D("2.7");
        T = D2.D("2.8");
        U = D2.D("2.9");
        V = D2.D("2.10");
        W = D2.D("2.11");
        X = kVar.D("302");
        Y = kVar.D("302.1");
        Z = kVar.D("302.2");
        a0 = kVar.D("302.3");
        k D3 = kVar.D("401");
        b0 = D3;
        c0 = D3.D("2");
        d0 = kVar.D("501");
        e0 = kVar.D("502");
        f0 = kVar.D("503");
        g0 = kVar.D("504");
        h0 = kVar.D("505");
        i0 = kVar.D("506");
        j0 = kVar.D("507");
        k0 = kVar.D("520");
        l0 = kVar.D("521");
        m0 = kVar.D("522");
    }
}
