package defpackage;

import org.bouncycastle.asn1.k;
/* renamed from: yp9  reason: default package */
/* loaded from: classes3.dex */
public interface yp9 {
    public static final k A;
    public static final k B;
    public static final k C;
    public static final k D;
    public static final k E;
    public static final k F;
    public static final k G;
    public static final k H;
    public static final k I;
    public static final k J;
    public static final k K;
    public static final k L;
    public static final k M;
    public static final k N;
    public static final k O;
    public static final k P;
    public static final k Q;
    public static final k R;
    public static final k S;
    public static final k T;
    public static final k U;
    public static final k V;
    public static final k W;
    public static final k X;
    public static final k Y;
    public static final k a;
    public static final k b;
    public static final k c;
    public static final k d;
    public static final k e;
    public static final k f;
    public static final k g;
    public static final k h;
    public static final k i;
    public static final k j;
    public static final k k;
    public static final k l;
    public static final k m;
    public static final k n;
    public static final k o;
    public static final k p;
    public static final k q;
    public static final k r;
    public static final k s;
    public static final k t;
    public static final k u;
    public static final k v;
    public static final k w;
    public static final k x;
    public static final k y;
    public static final k z;

    static {
        k kVar = new k("1.3.132.0");
        a = kVar;
        b = kVar.D("1");
        c = kVar.D("2");
        d = kVar.D("3");
        e = kVar.D("4");
        f = kVar.D("5");
        g = kVar.D("6");
        h = kVar.D("7");
        i = kVar.D("8");
        j = kVar.D("9");
        k = kVar.D("10");
        l = kVar.D("15");
        m = kVar.D("16");
        n = kVar.D("17");
        o = kVar.D("22");
        p = kVar.D("23");
        q = kVar.D("24");
        r = kVar.D("25");
        s = kVar.D("26");
        t = kVar.D("27");
        u = kVar.D("28");
        v = kVar.D("29");
        w = kVar.D("30");
        x = kVar.D("31");
        y = kVar.D("32");
        z = kVar.D("33");
        A = kVar.D("34");
        B = kVar.D("35");
        C = kVar.D("36");
        D = kVar.D("37");
        E = kVar.D("38");
        F = kVar.D("39");
        G = oac.f4;
        H = oac.l4;
        k kVar2 = new k("1.3.132.1");
        I = kVar2;
        J = kVar2.D("11.0");
        K = kVar2.D("11.1");
        L = kVar2.D("11.2");
        M = kVar2.D("11.3");
        N = kVar2.D("14.0");
        O = kVar2.D("14.1");
        P = kVar2.D("14.2");
        Q = kVar2.D("14.3");
        R = kVar2.D("15.0");
        S = kVar2.D("15.1");
        T = kVar2.D("15.2");
        U = kVar2.D("15.3");
        V = kVar2.D("16.0");
        W = kVar2.D("16.1");
        X = kVar2.D("16.2");
        Y = kVar2.D("16.3");
    }
}
